- name: docs
  description: Documentation pipelines
  build:
    provider: dkcicd
    pipelines:
    - name: techdocs-v1
      parameters:
        entityReference: default/component/b2b-suite
        sourceDir: ./
        indexFile: README.md
      when:
      - event: push
        source: branch
        regex: main
        path:
        - docs/**
      runtime: {}
